
package book_bank_mangt;

import java.sql.*;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;

//import java.text.SimpleDateFormat;
import java.util.Date;

public class Issue_book extends javax.swing.JFrame {

    Connection con = null;
    PreparedStatement pst = null;
    
    ResultSet rs = null;
    
    public Issue_book() {
        initComponents();
        con = DBconn.ConDB();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btn_search = new javax.swing.JButton();
        txt_book_name = new javax.swing.JTextField();
        txt_book_id = new javax.swing.JTextField();
        btn_search_id = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txt_user_id = new javax.swing.JTextField();
        btn_search_user_id = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btn_issue_book = new javax.swing.JButton();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jLabel6 = new javax.swing.JLabel();
        txt_user_name = new javax.swing.JTextField();
        btn_clear = new javax.swing.JButton();
        btn_back_to_home = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Book Name");

        jLabel2.setText("Book ID");

        btn_search.setText("Search");
        btn_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_searchActionPerformed(evt);
            }
        });

        btn_search_id.setText("Search_ID");
        btn_search_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_search_idActionPerformed(evt);
            }
        });

        jLabel3.setText("User ID");

        btn_search_user_id.setText("Search User");
        btn_search_user_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_search_user_idActionPerformed(evt);
            }
        });

        jLabel4.setText("Issue Date");

        jLabel5.setText("Due Date");

        btn_issue_book.setForeground(new java.awt.Color(51, 51, 255));
        btn_issue_book.setText("Issue Book");
        btn_issue_book.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_issue_bookActionPerformed(evt);
            }
        });

        jLabel6.setText("User Name");

        btn_clear.setText("Clear");
        btn_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clearActionPerformed(evt);
            }
        });

        btn_back_to_home.setText("Back");
        btn_back_to_home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_back_to_homeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_clear)
                        .addGap(29, 29, 29)
                        .addComponent(btn_issue_book)
                        .addGap(42, 42, 42)
                        .addComponent(btn_back_to_home))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txt_book_name, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addComponent(btn_search_id))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_user_id, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                            .addComponent(txt_book_id))
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_search)
                            .addComponent(btn_search_user_id)))
                    .addComponent(txt_user_name, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jDateChooser2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                        .addComponent(jDateChooser1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(132, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt_book_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_search_id))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_book_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_search))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_user_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_search_user_id))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txt_user_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jDateChooser2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_issue_book)
                    .addComponent(btn_clear)
                    .addComponent(btn_back_to_home))
                .addGap(40, 40, 40))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_searchActionPerformed
        // TODO add your handling code here:
        try {
            pst=con.prepareStatement("SELECT * FROM book_table where book_ID=?");
            pst.setString(1, txt_book_id.getText());
            rs=pst.executeQuery();
            if(rs.next()){
                    txt_book_name.setText(rs.getString("Book_name"));}
            else{
                txt_book_id.setText("");
                txt_book_name.setText("");
                JOptionPane.showMessageDialog(this, "Please Enter Valied Book ID");
                
            }
        }
        catch(Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_btn_searchActionPerformed

    private void btn_search_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_search_idActionPerformed
        // TODO add your handling code here:
        try {
            pst=con.prepareStatement("SELECT * FROM book_table where Book_name=?");
            pst.setString(1, txt_book_name.getText());
            rs=pst.executeQuery();
            if(rs.next())
                    txt_book_id.setText(rs.getString("book_ID"));
            else{
                txt_book_name.setText("");
                JOptionPane.showMessageDialog(this, "Please Enter Valied Book name");}
        }
        catch(Exception e){
            System.out.println(e);
        }
        
    }//GEN-LAST:event_btn_search_idActionPerformed

    private void btn_search_user_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_search_user_idActionPerformed
        // TODO add your handling code here:
        try {
            pst=con.prepareStatement("SELECT * FROM Student_table where stu_ID=?");
            pst.setString(1, txt_user_id.getText());
            rs=pst.executeQuery();
            if(rs.next()){
                    //txt_book_name.setText(rs.getString("Book_name"));
                    JOptionPane.showMessageDialog(this, "Yes, valid User ID ");
                    pst=con.prepareStatement("SELECT * FROM Student_table where Stu_ID=?");
                    pst.setString(1, txt_user_id.getText());
                    rs=pst.executeQuery();
                    if(rs.next()){
                        txt_user_name.setText(rs.getString("stu_name"));}
            
            }
            else{
                //txt_book_id.setText("");
                JOptionPane.showMessageDialog(this, "Invalid User ID");
                txt_user_name.setText("");
                txt_user_id.setText("");
            
            }
        }
        catch(Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_btn_search_user_idActionPerformed

    private void btn_issue_bookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_issue_bookActionPerformed
        // TODO add your handling code here:
          SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd"); // Choose your desired format
            String formattedDate1 = jDateChooser1.getDate() != null ? sdf.format(jDateChooser1.getDate()) : "";
            String formattedDate2 = jDateChooser2.getDate() != null ? sdf.format(jDateChooser2.getDate()) : "";
      
        
        if (txt_user_id.getText().trim().isEmpty() || txt_user_name.getText().trim().isEmpty() ||
    txt_book_id.getText().trim().isEmpty() || txt_book_name.getText().trim().isEmpty() ||
    formattedDate1 == null || formattedDate2 == null) {

    JOptionPane.showMessageDialog(null, "Please enter all details before submitting.");
}
        else{
            
        
        try{
            
          
            String sql = "INSERT INTO Issued_books1 VALUES (?,?,?,?,?,?,?);";
            pst = con.prepareStatement(sql);
            pst.setString(1, txt_user_id.getText());
            pst.setString(2,txt_user_name.getText());
            pst.setString(3, txt_book_id.getText());
            pst.setString(4, txt_book_name.getText());
            

            pst.setString(5, formattedDate1 );
            pst.setString(6, formattedDate2);
            
            
            pst.setString(7,"No");
            
            pst.executeUpdate();
            
            
            //System.out.println("New User Registration done..!");
            JOptionPane.showMessageDialog(null, "Book Issued Successfully!");
            dispose();
            java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
              new Admin_activity().setVisible(true);
             }
        });
            
        }
        catch(Exception e){
            System.out.println("Registration into DB Failed" + e);
        }
        
        }
    }                                       

    private void btn_backActionPerformed(java.awt.event.ActionEvent evt) {                                         
        dispose();
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin_activity().setVisible(true);
            }
        });
        
        
    }//GEN-LAST:event_btn_issue_bookActionPerformed

    private void btn_back_to_homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_back_to_homeActionPerformed
        // TODO add your handling code here:
        dispose();
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin_activity().setVisible(true);
            }
        });
    }//GEN-LAST:event_btn_back_to_homeActionPerformed

    private void btn_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clearActionPerformed
        // TODO add your handling code here:
        txt_book_id.setText("");
        txt_book_name.setText("");
        txt_user_id.setText("");
        txt_user_name.setText("");
        jDateChooser1.setDate(null);
        jDateChooser2.setDate(null);
    }//GEN-LAST:event_btn_clearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Issue_book.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Issue_book.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Issue_book.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Issue_book.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Issue_book().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_back_to_home;
    private javax.swing.JButton btn_clear;
    private javax.swing.JButton btn_issue_book;
    private javax.swing.JButton btn_search;
    private javax.swing.JButton btn_search_id;
    private javax.swing.JButton btn_search_user_id;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField txt_book_id;
    private javax.swing.JTextField txt_book_name;
    private javax.swing.JTextField txt_user_id;
    private javax.swing.JTextField txt_user_name;
    // End of variables declaration//GEN-END:variables
}
